// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type InjectionType<A extends Plugin> = A extends {default: Plugin<infer T>} ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_8cc6cd5caf0b6192cfd05fb7c1867450/node_modules/nuxt/dist/app/plugins/revive-payload.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_8cc6cd5caf0b6192cfd05fb7c1867450/node_modules/nuxt/dist/head/runtime/plugins/unhead.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_8cc6cd5caf0b6192cfd05fb7c1867450/node_modules/nuxt/dist/pages/runtime/plugins/router.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_8cc6cd5caf0b6192cfd05fb7c1867450/node_modules/nuxt/dist/app/plugins/payload.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_8cc6cd5caf0b6192cfd05fb7c1867450/node_modules/nuxt/dist/app/plugins/navigation-repaint.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_8cc6cd5caf0b6192cfd05fb7c1867450/node_modules/nuxt/dist/app/plugins/check-outdated-build.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_8cc6cd5caf0b6192cfd05fb7c1867450/node_modules/nuxt/dist/app/plugins/revive-payload.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_8cc6cd5caf0b6192cfd05fb7c1867450/node_modules/nuxt/dist/app/plugins/chunk-reload.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_8cc6cd5caf0b6192cfd05fb7c1867450/node_modules/nuxt/dist/pages/runtime/plugins/prefetch.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+i18n@10.2.3_@vue+compiler-dom@3.5.30_db0@0.3.4_eslint@10.1.0_jiti@2.6.1__ioredi_4bc412c111c1bf2fce3c67d6bc5885ee/node_modules/@nuxtjs/i18n/dist/runtime/plugins/switch-locale-path-ssr.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+i18n@10.2.3_@vue+compiler-dom@3.5.30_db0@0.3.4_eslint@10.1.0_jiti@2.6.1__ioredi_4bc412c111c1bf2fce3c67d6bc5885ee/node_modules/@nuxtjs/i18n/dist/runtime/plugins/route-locale-detect.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+i18n@10.2.3_@vue+compiler-dom@3.5.30_db0@0.3.4_eslint@10.1.0_jiti@2.6.1__ioredi_4bc412c111c1bf2fce3c67d6bc5885ee/node_modules/@nuxtjs/i18n/dist/runtime/plugins/preload.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+i18n@10.2.3_@vue+compiler-dom@3.5.30_db0@0.3.4_eslint@10.1.0_jiti@2.6.1__ioredi_4bc412c111c1bf2fce3c67d6bc5885ee/node_modules/@nuxtjs/i18n/dist/runtime/plugins/dev.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+i18n@10.2.3_@vue+compiler-dom@3.5.30_db0@0.3.4_eslint@10.1.0_jiti@2.6.1__ioredi_4bc412c111c1bf2fce3c67d6bc5885ee/node_modules/@nuxtjs/i18n/dist/runtime/plugins/i18n.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+extensions@3.20.4_@tiptap+core@3.20.4_@tiptap+pm@3.20.4__@tiptap_bb54c58e453736da07c8abe6b4fdb040/node_modules/@nuxt/ui/dist/runtime/plugins/colors.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+color-mode@3.5.2_magicast@0.5.2/node_modules/@nuxtjs/color-mode/dist/runtime/plugin.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+color-mode@3.5.2_magicast@0.5.2/node_modules/@nuxtjs/color-mode/dist/runtime/plugin.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+icon@2.2.1_magicast@0.5.2_vite@7.3.1_jiti@2.6.1_lightningcss@1.32.0_terser@5.46.1_969d979b4188a43ce1f32542dc914b68/node_modules/@nuxt/icon/dist/runtime/plugin.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+i18n@10.2.3_@vue+compiler-dom@3.5.30_db0@0.3.4_eslint@10.1.0_jiti@2.6.1__ioredi_4bc412c111c1bf2fce3c67d6bc5885ee/node_modules/@nuxtjs/i18n/dist/runtime/plugins/ssg-detect.js")>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }

  interface NuxtAppLiterals {
    pluginName: 'nuxt:revive-payload:client' | 'nuxt:head' | 'nuxt:router' | 'nuxt:payload' | 'nuxt:revive-payload:server' | 'nuxt:chunk-reload' | 'nuxt:global-components' | 'nuxt:prefetch' | 'i18n:plugin:switch-locale-path-ssr' | 'i18n:plugin:route-locale-detect' | 'i18n:plugin:preload' | 'i18n:dev' | 'i18n:plugin' | '@nuxt/icon' | 'i18n:plugin:ssg-detect'
  }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
