// Generated by auto imports
export {}
declare global {
  const useRuntimeConfig: (event?: import('h3').H3Event) => import('nuxt/schema').RuntimeConfig
  const useAppConfig: () => import('nuxt/schema').AppConfig
  const defineAppConfig: <C extends import('nuxt/schema').AppConfigInput>(config: C) => C
  const createError: typeof import('h3')['createError']
  const setResponseStatus: typeof import('h3')['setResponseStatus']
  const formatCurrency: typeof import('../../shared/utils/format-currency').formatCurrency
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Product } from '../../shared/types/product'
  import('../../shared/types/product')
}